# Generated by Django 3.0.6 on 2020-05-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('Code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('Location', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Longitude', models.FloatField(max_length=10)),
                ('Latitude', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('Event_Id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('Accident_number', models.CharField(max_length=10)),
                ('Date', models.DateTimeField()),
                ('Injurity_severity', models.CharField(max_length=10)),
                ('Investigation_type', models.CharField(max_length=10)),
                ('Aircraft_damage', models.TextField(max_length=15)),
                ('Weather_condition', models.CharField(max_length=3)),
                ('Broad_phase', models.CharField(max_length=15)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('Registration_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Aircraft_category', models.CharField(max_length=20)),
                ('Model', models.CharField(max_length=20)),
                ('Number_engine', models.IntegerField()),
                ('Engine_type', models.CharField(max_length=15)),
                ('Make', models.CharField(max_length=30)),
                ('FAR', models.CharField(max_length=30)),
                ('Schedule', models.CharField(max_length=15)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Airport')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Event')),
            ],
        ),
    ]
